/*
 * This file is generated by jOOQ.
 */
package com.akobor.r2dbcdemo.tables.references


import com.akobor.r2dbcdemo.tables.Account
import com.akobor.r2dbcdemo.tables.Address



/**
 * The table <code>r2dbc-poc.account</code>.
 */
val ACCOUNT: Account = Account.ACCOUNT

/**
 * The table <code>r2dbc-poc.address</code>.
 */
val ADDRESS: Address = Address.ADDRESS
