/*
 * This file is generated by jOOQ.
 */
package com.akobor.r2dbcdemo


import kotlin.collections.List

import org.jooq.Schema
import org.jooq.impl.CatalogImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DefaultCatalog : CatalogImpl("") {
    companion object {

        /**
         * The reference instance of <code>DEFAULT_CATALOG</code>
         */
        public val DEFAULT_CATALOG: DefaultCatalog = DefaultCatalog()
    }

    /**
     * The schema <code>r2dbc-poc</code>.
     */
    val `R2DBC-POC`: R2dbcPoc get(): R2dbcPoc = com.akobor.r2dbcdemo.R2dbcPoc.`R2DBC-POC`

    override fun getSchemas(): List<Schema> = listOf(
        com.akobor.r2dbcdemo.R2dbcPoc.`R2DBC-POC`
    )
}
