/*
 * This file is generated by jOOQ.
 */
package com.akobor.r2dbcdemo.tables


import com.akobor.r2dbcdemo.keys.ACCOUNT_PKEY
import com.akobor.r2dbcdemo.tables.records.AccountRecord

import java.time.LocalDateTime
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row3
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Account(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, AccountRecord>?,
    aliased: Table<AccountRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<AccountRecord>(
    alias,
    com.akobor.r2dbcdemo.R2dbcPoc.`R2DBC-POC`,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>r2dbc-poc.account</code>
         */
        val ACCOUNT: Account = Account()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AccountRecord> = AccountRecord::class.java

    /**
     * The column <code>r2dbc-poc.account.id</code>.
     */
    val ID: TableField<AccountRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>r2dbc-poc.account.name</code>.
     */
    val NAME: TableField<AccountRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>r2dbc-poc.account.deleted_at</code>.
     */
    val DELETED_AT: TableField<AccountRecord, LocalDateTime?> = createField(DSL.name("deleted_at"), SQLDataType.LOCALDATETIME(6), this, "")

    private constructor(alias: Name, aliased: Table<AccountRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<AccountRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>r2dbc-poc.account</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>r2dbc-poc.account</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>r2dbc-poc.account</code> table reference
     */
    constructor(): this(DSL.name("account"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, AccountRecord>): this(Internal.createPathAlias(child, key), child, key, ACCOUNT, null)
    override fun getSchema(): Schema? = if (aliased()) null else com.akobor.r2dbcdemo.R2dbcPoc.`R2DBC-POC`
    override fun getIdentity(): Identity<AccountRecord, Long?> = super.getIdentity() as Identity<AccountRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<AccountRecord> = ACCOUNT_PKEY
    override fun `as`(alias: String): Account = Account(DSL.name(alias), this)
    override fun `as`(alias: Name): Account = Account(alias, this)
    override fun `as`(alias: Table<*>): Account = Account(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Account = Account(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Account = Account(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Account = Account(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row3<Long?, String?, LocalDateTime?> = super.fieldsRow() as Row3<Long?, String?, LocalDateTime?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Long?, String?, LocalDateTime?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Long?, String?, LocalDateTime?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
