/*
 * This file is generated by jOOQ.
 */
package com.akobor.r2dbcdemo.tables


import com.akobor.r2dbcdemo.indexes.IDX_ADDRESS_ACCOUNT_ID
import com.akobor.r2dbcdemo.keys.ADDRESS_PKEY
import com.akobor.r2dbcdemo.keys.ADDRESS__ADDRESS_ACCOUNT_ID_FKEY
import com.akobor.r2dbcdemo.tables.records.AddressRecord

import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row3
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Address(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, AddressRecord>?,
    aliased: Table<AddressRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<AddressRecord>(
    alias,
    com.akobor.r2dbcdemo.R2dbcPoc.`R2DBC-POC`,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>r2dbc-poc.address</code>
         */
        val ADDRESS: Address = Address()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AddressRecord> = AddressRecord::class.java

    /**
     * The column <code>r2dbc-poc.address.id</code>.
     */
    val ID: TableField<AddressRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>r2dbc-poc.address.account_id</code>.
     */
    val ACCOUNT_ID: TableField<AddressRecord, Long?> = createField(DSL.name("account_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>r2dbc-poc.address.full_address</code>.
     */
    val FULL_ADDRESS: TableField<AddressRecord, String?> = createField(DSL.name("full_address"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<AddressRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<AddressRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>r2dbc-poc.address</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>r2dbc-poc.address</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>r2dbc-poc.address</code> table reference
     */
    constructor(): this(DSL.name("address"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, AddressRecord>): this(Internal.createPathAlias(child, key), child, key, ADDRESS, null)
    override fun getSchema(): Schema? = if (aliased()) null else com.akobor.r2dbcdemo.R2dbcPoc.`R2DBC-POC`
    override fun getIndexes(): List<Index> = listOf(IDX_ADDRESS_ACCOUNT_ID)
    override fun getIdentity(): Identity<AddressRecord, Long?> = super.getIdentity() as Identity<AddressRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<AddressRecord> = ADDRESS_PKEY
    override fun getReferences(): List<ForeignKey<AddressRecord, *>> = listOf(ADDRESS__ADDRESS_ACCOUNT_ID_FKEY)

    private lateinit var _account: Account

    /**
     * Get the implicit join path to the <code>r2dbc-poc.account</code> table.
     */
    fun account(): Account {
        if (!this::_account.isInitialized)
            _account = Account(this, ADDRESS__ADDRESS_ACCOUNT_ID_FKEY)

        return _account;
    }

    val account: Account
        get(): Account = account()
    override fun `as`(alias: String): Address = Address(DSL.name(alias), this)
    override fun `as`(alias: Name): Address = Address(alias, this)
    override fun `as`(alias: Table<*>): Address = Address(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Address = Address(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Address = Address(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Address = Address(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row3<Long?, Long?, String?> = super.fieldsRow() as Row3<Long?, Long?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Long?, Long?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Long?, Long?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
