/*
 * This file is generated by jOOQ.
 */
package com.akobor.r2dbcdemo.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime

import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.GenerationType
import javax.persistence.Id
import javax.persistence.Table
import javax.validation.constraints.NotNull
import javax.validation.constraints.Size


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
@Entity
@Table(
    name = "account",
    schema = "r2dbc-poc"
)
data class AccountPojo(
    @get:Id
    @get:GeneratedValue(strategy = GenerationType.IDENTITY)
    @get:Column(name = "id", nullable = false, precision = 64)
    val id: Long? = null,
    @get:Column(name = "name", nullable = false, length = 255)
    @get:NotNull
    @get:Size(max = 255)
    val name: String? = null,
    @get:Column(name = "deleted_at", precision = 6)
    val deletedAt: LocalDateTime? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("AccountPojo (")

        sb.append(id)
        sb.append(", ").append(name)
        sb.append(", ").append(deletedAt)

        sb.append(")")
        return sb.toString()
    }
}
