/*
 * This file is generated by jOOQ.
 */
package com.akobor.r2dbcdemo.tables.pojos


import java.io.Serializable

import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.GenerationType
import javax.persistence.Id
import javax.persistence.Index
import javax.persistence.Table
import javax.validation.constraints.NotNull
import javax.validation.constraints.Size


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
@Entity
@Table(
    name = "address",
    schema = "r2dbc-poc",
    indexes = [
        Index(name = "idx_address_account_id", columnList = "account_id ASC")
    ]
)
data class AddressPojo(
    @get:Id
    @get:GeneratedValue(strategy = GenerationType.IDENTITY)
    @get:Column(name = "id", nullable = false, precision = 64)
    val id: Long? = null,
    @get:Column(name = "account_id", nullable = false, precision = 64)
    @get:NotNull
    val accountId: Long? = null,
    @get:Column(name = "full_address", nullable = false, length = 255)
    @get:NotNull
    @get:Size(max = 255)
    val fullAddress: String? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("AddressPojo (")

        sb.append(id)
        sb.append(", ").append(accountId)
        sb.append(", ").append(fullAddress)

        sb.append(")")
        return sb.toString()
    }
}
